### ISSUE TITLE
why IGPU shou 5200?

### ISSUE THREAD

**Issue by luhua98989898** [samleong123/i5-4570-B85MG-HD4600-BigSur-Opencore-EFI#1]
why show IGPU 5200? not 4600

**Comment by samleong123** [comment]
Spoof as Iris Pro 5200 so QE/CI will be working 
Its doesn't matter
![Screenshot 2021-05-03 at 10 10 32](https://user-images.githubusercontent.com/58818070/116836074-cd071f80-abf7-11eb-9c6d-a9d03299085c.png)
