### ISSUE TITLE
Do you have any plan to support macOS Monterey(12.2)?

### ISSUE THREAD

**Issue by luoling8192** [samleong123/i5-4570-B85MG-HD4600-BigSur-Opencore-EFI#2]
I tried to update my opencore and lilu version to newer, but it didn't work on my computer.
My computer configuration is same to you.
Thanks!

**Comment by samleong123** [comment]
Nope , i already moved back to Windows since some software compability 
Currently on Windows 10 LTSC 2021 , if there's any planning to support it i will reopen this issue
